name: html

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Ruby Gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Check unrolled code is up to date
      run: |
        bundle exec rake code
        if [ -z "$(git status --porcelain)" ]; then
          echo "Unrolled code is in sync with code branches"
        else 
          >&2 echo "One or more code branches are not in sync with unrolled commits."
          git status
          >&2 echo "Either you need to run `rake code` and commit the changes, or you've forgotten to push a code branch"
        fi
    - name: Generate HTML pages using asciidoc
      run: 
        shots=1 bundle exec rake html
    - name: Create GH Pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: public
