name: html

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: failure()
      with:
        type: ${{ job.status }}
        job_name: '*GitHub Actions HTML build*'
        channel: '#school-devs'
        url: ${{ secrets.SLACK_WEBHOOK_URL }}
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install Ruby Gems
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Check unrolled code is up to date
      run: |
        bundle exec rake code
    - name: Generate HTML pages using asciidoc
      run: 
        shots=1 bundle exec rake html
    - name: Create GH Pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: public
